name: CI java&sql
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
  
jobs:
  Build:
    runs-on: self-hosted 
    steps:
    - uses: actions/checkout@v3
    - name: install 
      run:  docker-compose up -d

  Test:
    needs: Build
    runs-on: self-hosted
    steps:
    - name: test 
      run: sleep 10 && curl localhost:3000

  Package:
   needs: Test
   runs-on: self-hosted
   steps:
   - name: JFrog
     run: docker push jfogedemo.jfrog.io/appbenakiva-docker/react-java0mysql_frontend && docker push jfogedemo.jfrog.io/appbenakiva-docker/react-java0mysql_backend
    
  

